import Head from 'next/head'
import { Container, Heading, Tabs, TabList, TabPanels, Tab, TabPanel } from "@chakra-ui/react";
import { useEffect, useState, Fragment } from 'react';
import { axiosInstance } from "@/lib/axios"

/*
formik -> handle form
yup -> validate
tanstack-query -> manage api calls (cahcing, state, dll);
*/

export default function Home() {
const [transaksis, setTransaksis] = useState(null);

const fetchTransaksi = async () =>{
  try {
    const transaksiResponse = await axiosInstance.get("/settlement");
    setTransaksis(transaksiResponse.data);
  } catch (error) {
    console.log(error);
  }
};

const renderTransaksi = () => {
  return transaksis.map((transaksi) => {
    return (
      <TabPanels  key={transaksi.id}>
        <div>{transaksi.id}</div>
        <div>{transaksi.kartu}</div>
        <div>{transaksi.traceNumber}</div>
        <div>{transaksi.date}</div>
        <div>{transaksi.refNumber}</div>
        <div>{transaksi.totalHarga}</div>
      </TabPanels>
    );
  });
};


useEffect(() => {
  fetchTransaksi();
}, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="widTab=device-widTab, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>
            Hello World
          </Heading>
          <Tabs>
            <TabList>
                <Tab>ID</Tab>
                <Tab>Nama</Tab>
                <Tab>Harga</Tab>
                <Tab>TraceNumber</Tab>
            </TabList>
            <TabList>
              <Tab>{renderTransaksi()}</Tab>
            </TabList>
          </Tabs>
        </Container>
      </main>
    </>
  )
}
